android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
# Increase memory for R8/ProGuard and Kotlin compiler daemon
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
org.gradle.workers.max=2
org.gradle.daemon.idleTimeout=60000
android.enableR8.fullMode=false
org.gradle.configuration-cache=true

